### ISSUE TITLE
Help file available?

### ISSUE THREAD

**Issue by Naadir-Ganief** [marclegeay/omics-visualizer#1]
Hi, i installed your plugin on cytoscape, 
is there a help file available, to see the formats for import files

thanks

**Comment by marclegeay** [comment]
Hi,
Thank you for using the app.

There is no help file available I am sorry.
You can import every format that Cytoscape allows you to import tables: Excel sheets and text-delimited files.

Best.

**Comment by marclegeay** [comment]
Hi,

We now have training exercise online if you want: https://jensenlab.org/training/omicsvisualizer/.

Best.
